# Generated by Django 4.2.9 on 2026-05-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('car_name', models.CharField(max_length=100, verbose_name='Avtomobil nomi')),
                ('car_number', models.CharField(max_length=20, verbose_name='Avtomobil raqami')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('working', 'Ishlamoqda'), ('not_working', 'Ishlamayapti'), ('pending', 'Javob bermagan')], default='pending', max_length=20, verbose_name='Status')),
                ('location', models.CharField(blank=True, help_text='mahalla yoki oydin', max_length=50, null=True, verbose_name='Joylashuv')),
                ('moving_direction', models.CharField(blank=True, max_length=50, null=True, verbose_name="Harakat yo'nalishi")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_statuses', to='drivers.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Kunlik status',
                'verbose_name_plural': 'Kunlik statuslar',
                'ordering': ['-date'],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
