# Generated by Django 4.2.9 on 2026-05-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Elon matni')),
                ('sent_by', models.BigIntegerField(verbose_name='Yuboruvchi Telegram ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Qabul qiluvchilar soni')),
            ],
            options={
                'verbose_name': 'Elon',
                'verbose_name_plural': 'Elonlar',
                'ordering': ['-sent_at'],
            },
        ),
    ]
